name: CSP Scraper

on:
  schedule:
#    - cron: "0 5 * * *"
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install
          npx playwright install chromium

      - name: Run scraper
        run: node csp_scout.js
